import { AppModal } from "@/components/common/AppModal";

interface TransactionReceiptModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  reference?: string;
  amount?: number;
  type?: string;
  date?: string;
  accountName?: string;
  service?: string;
  description?: string;
  paymentMethod?: string;
  status?: string;
}

export function TransactionReceiptModal({
  open,
  onOpenChange,
  reference = "TXN-2026-008466",
  amount = 184999,
  type = "Marketplace Purchase",
  date = "22 Jun 2026 · 11:45 AM",
  accountName = "Yusuf Adam Baba",
  service = "Marketplace Order",
  description = "Hikvision DS-2CD2143G2",
  paymentMethod = "Simkash Wallet",
  status = "COMPLETED",
}: TransactionReceiptModalProps) {
  const isCredit = amount > 0;
  const formattedAmount = `${isCredit ? "+" : "₦"}${Math.abs(amount).toLocaleString()}`;

  const handleDownloadPdf = () => {
    alert(`Downloading PDF receipt for ${reference}...`);
  };

  const handleShare = () => {
    if (navigator.share) {
      navigator.share({
        title: `Simkash Receipt ${reference}`,
        text: `Simkash Official Receipt for ₦${Math.abs(amount).toLocaleString()}`,
        url: window.location.href,
      }).catch(() => {});
    } else {
      alert("Sharing link copied to clipboard!");
    }
  };

  return (
    <AppModal
      open={open}
      onOpenChange={onOpenChange}
      title="Transaction Receipt"
      description={reference}
      size="md"
    >
      <div className="space-y-4 pt-1">
        {/* Official Receipt Card */}
        <div className="rounded-2xl border-2 border-[#0F152A] bg-white p-6 text-xs space-y-4 shadow-sm text-center">
          <div>
            <h3 className="font-extrabold text-[#0F152A] text-base tracking-wider uppercase">
              SIMKASH
            </h3>
            <span className="text-[10px] font-bold text-[#8C909B] uppercase tracking-widest block">
              OFFICIAL RECEIPT
            </span>
          </div>

          <div className="border-t border-[#E2ECF6] pt-3">
            <h2 className="text-3xl font-extrabold text-[#0F152A]">{formattedAmount}</h2>
            <p className="text-xs text-[#8C909B] font-medium mt-0.5">{type}</p>
          </div>

          {/* Details List */}
          <div className="divide-y divide-[#E2ECF6] border-t border-b border-[#E2ECF6] py-1 text-xs text-left">
            <div className="flex justify-between py-2">
              <span className="text-[#8C909B]">Date</span>
              <span className="font-bold text-[#0F152A]">{date}</span>
            </div>
            <div className="flex justify-between py-2">
              <span className="text-[#8C909B]">Reference</span>
              <span className="font-mono font-bold text-[#0F152A]">{reference}</span>
            </div>
            <div className="flex justify-between py-2">
              <span className="text-[#8C909B]">Account</span>
              <span className="font-bold text-[#0F152A]">{accountName}</span>
            </div>
            <div className="flex justify-between py-2">
              <span className="text-[#8C909B]">Service</span>
              <span className="font-bold text-[#0F152A]">{service}</span>
            </div>
            <div className="flex justify-between py-2">
              <span className="text-[#8C909B]">Description</span>
              <span className="font-bold text-[#0F152A]">{description}</span>
            </div>
            <div className="flex justify-between py-2">
              <span className="text-[#8C909B]">Payment</span>
              <span className="font-bold text-[#0F152A]">{paymentMethod}</span>
            </div>
            <div className="flex justify-between py-2">
              <span className="text-[#8C909B]">Status</span>
              <span className="font-extrabold text-[#10B981]">✓ {status}</span>
            </div>
          </div>

          <div className="text-[10px] text-[#8C909B] space-y-0.5">
            <p>This is an official receipt generated by Simkash</p>
            <p className="font-bold text-[#2563EB]">simkash.com</p>
          </div>
        </div>

        {/* Footer Action Buttons */}
        <div className="flex items-center justify-end border-t border-[#E2ECF6] pt-4 gap-2.5">
          <button
            type="button"
            onClick={() => onOpenChange(false)}
            className="rounded-xl border border-[#E2ECF6] px-5 py-2.5 text-xs font-bold text-[#0F152A] hover:bg-slate-50"
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={handleDownloadPdf}
            className="rounded-xl bg-[#2563EB] px-6 py-2.5 text-xs font-bold text-white shadow-md hover:bg-blue-700"
          >
            Download PDF
          </button>
          <button
            type="button"
            onClick={handleShare}
            className="rounded-xl border border-[#E2ECF6] px-5 py-2.5 text-xs font-bold text-[#0F152A] hover:bg-slate-50"
          >
            Share
          </button>
        </div>
      </div>
    </AppModal>
  );
}
