import { useState, useMemo } from "react";
import { Search, MessageSquare } from "lucide-react";
import { APP_COLORS } from "@/constants/colors";
import type { ScPerformanceRowItem } from "../../../types/regional-manager-performance.types";
import { RM_SC_PERFORMANCE_DATA } from "../../../data/regional-manager-performance.data";


interface RmCommissionByScListProps {
  onContactSc: (sc: ScPerformanceRowItem) => void;
}

export function RmCommissionByScList({ onContactSc }: RmCommissionByScListProps) {
  const [search, setSearch] = useState("");
  const totalCommission = 284000;

  const filteredList = useMemo(() => {
    return RM_SC_PERFORMANCE_DATA.filter(
      (sc) =>
        sc.scName.toLowerCase().includes(search.toLowerCase()) ||
        sc.state.toLowerCase().includes(search.toLowerCase())
    );
  }, [search]);

  return (
    <div
      className="rounded-2xl border shadow-xs overflow-hidden"
      style={{
        backgroundColor: APP_COLORS.backgrounds.background,
        borderColor: APP_COLORS.greys.stroke,
      }}
    >
      <div className="p-4 border-b space-y-2.5" style={{ borderColor: APP_COLORS.greys.stroke }}>
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
          <div>
            <h3 className="text-sm sm:text-base font-bold" style={{ color: APP_COLORS.texts.primary }}>
              Commission Generated by State Coordinator
            </h3>
            <p className="text-xs font-medium" style={{ color: APP_COLORS.texts.slate }}>
              Regional Manager overrides accrued per coordinator zone
            </p>
          </div>
          <div className="relative w-full sm:w-60">
            <Search className="w-3.5 h-3.5 absolute left-3 top-1/2 -translate-y-1/2" style={{ color: APP_COLORS.texts.slate }} />
            <input
              type="text"
              placeholder="Search SC..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full pl-9 pr-3 py-1.5 rounded-xl border text-xs outline-none focus:border-blue-500"
              style={{
                borderColor: APP_COLORS.greys.stroke,
                backgroundColor: APP_COLORS.backgrounds.surface,
                color: APP_COLORS.texts.primary,
              }}
            />
          </div>
        </div>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-left text-xs">
          <thead
            style={{
              backgroundColor: APP_COLORS.backgrounds.surface,
              borderBottom: `1px solid ${APP_COLORS.greys.stroke}`,
              color: APP_COLORS.texts.slate,
            }}
          >
            <tr>
              <th className="py-2.5 px-3 font-bold w-12 text-center">#</th>
              <th className="py-2.5 px-3 font-bold">State Coordinator</th>
              <th className="py-2.5 px-3 font-bold text-right">Activations</th>
              <th className="py-2.5 px-3 font-bold text-right">Avg Override</th>
              <th className="py-2.5 px-3 font-bold text-right">Commission Earned</th>
              <th className="py-2.5 px-3 font-bold w-28 text-center">Share</th>
              <th className="py-2.5 px-3 font-bold text-right">Action</th>
            </tr>
          </thead>
          <tbody className="divide-y" style={{ borderColor: APP_COLORS.greys.stroke }}>
            {filteredList.map((sc, idx) => {
              const share = Math.round((sc.commissionEarned / totalCommission) * 100);
              const overrideRate = (sc.commissionEarned / sc.activations).toFixed(2);

              return (
                <tr key={sc.id} className="hover:bg-slate-50/70 transition-colors">
                  <td className="py-2.5 px-3 text-center font-bold text-slate-500">
                    {idx + 1}
                  </td>
                  <td className="py-2.5 px-3">
                    <span className="font-bold block" style={{ color: APP_COLORS.texts.primary }}>
                      {sc.scName}
                    </span>
                    <span className="text-[11px] text-slate-400 block">{sc.state} State</span>
                  </td>
                  <td className="py-2.5 px-3 text-right font-medium" style={{ color: APP_COLORS.texts.primary }}>
                    {sc.activations.toLocaleString()}
                  </td>
                  <td className="py-2.5 px-3 text-right font-medium text-slate-500">
                    ₦{overrideRate} / act
                  </td>
                  <td className="py-2.5 px-3 text-right font-black" style={{ color: APP_COLORS.greens.secondary }}>
                    ₦{sc.commissionEarned.toLocaleString()}
                  </td>
                  <td className="py-2.5 px-3">
                    <div className="flex items-center gap-1.5 justify-center">
                      <div className="w-12 h-1.5 rounded-full bg-slate-100 overflow-hidden">
                        <div
                          className="h-full rounded-full"
                          style={{
                            width: `${share * 3}%`,
                            backgroundColor: APP_COLORS.blues.interactiveCta,
                          }}
                        />
                      </div>
                      <span className="text-[10px] font-bold text-slate-500">{share}%</span>
                    </div>
                  </td>
                  <td className="py-2.5 px-3 text-right">
                    <button
                      type="button"
                      onClick={() => onContactSc(sc)}
                      className="p-1 rounded-lg border hover:bg-slate-100 text-slate-600 inline-flex items-center"
                      style={{ borderColor: APP_COLORS.greys.stroke }}
                      title="Contact SC"
                    >
                      <MessageSquare className="w-3.5 h-3.5" />
                    </button>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}
