import { useState } from "react";
import { AppModal } from "@/components/common/AppModal";
import { openNotification } from "@/utils/notifications";

const simTypes = ["POS SIM", "CCTV SIM", "GPS SIM", "Router SIM"];
const networks = ["MTN", "Airtel", "Glo", "T2", "No preference"];

export function RequestSimModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [type, setType] = useState(simTypes[0]); const [network, setNetwork] = useState("No preference"); const [quantity, setQuantity] = useState(1); const [delivery, setDelivery] = useState("Agent Visit");
  const [state, setState] = useState(""); const [area, setArea] = useState(""); const [street, setStreet] = useState(""); const [landmark, setLandmark] = useState(""); const [notes, setNotes] = useState("");
  const close = () => { setType(simTypes[0]); setNetwork("No preference"); setQuantity(1); setDelivery("Agent Visit"); setState(""); setArea(""); setStreet(""); setLandmark(""); setNotes(""); onClose(); };
  const submit = () => { openNotification({ state: "info", title: "Request form complete", description: "SIM request submission is not connected to a backend endpoint yet." }); close(); };
  return <AppModal open={open} onOpenChange={(v) => !v && close()} title="Request a SIM" description="A Simkash agent will fulfil your request" size="lg"><div className="max-h-[70vh] space-y-4 overflow-y-auto pr-1">
    <p className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs text-[#2563EB]">Submit a SIM request and a Simkash agent in your area will contact you to activate your SIM.</p>
    <section><p className="mb-2 text-[10px] font-bold uppercase text-[#8C909B]">SIM type</p><div className="grid grid-cols-2 gap-2">{simTypes.map((item) => <button key={item} onClick={() => setType(item)} className={`rounded-xl border p-3 text-left text-sm font-semibold ${type === item ? "border-[#2563EB] bg-blue-50 text-[#2563EB]" : "border-[#E2ECF6]"}`}>{item}<small className="mt-1 block text-xs font-normal text-[#8C909B]">For {item.toLowerCase()}</small></button>)}</div></section>
    <section><p className="mb-2 text-[10px] font-bold uppercase text-[#8C909B]">Preferred network</p><div className="flex flex-wrap gap-2">{networks.map((item) => <button key={item} onClick={() => setNetwork(item)} className={`rounded-full border px-3 py-1.5 text-xs ${network === item ? "border-[#2563EB] bg-blue-50 text-[#2563EB]" : "border-[#E2ECF6]"}`}>{item}</button>)}</div></section>
    <div className="flex items-center justify-between text-sm"><span>Number of SIM cards <small className="block text-xs text-[#8C909B]">Maximum 5 SIM cards per request</small></span><div className="flex items-center"><button onClick={() => setQuantity(Math.max(1, quantity - 1))} className="rounded-l-lg border border-[#E2ECF6] px-3 py-2">−</button><span className="border-y border-[#E2ECF6] px-4 py-2">{quantity}</span><button onClick={() => setQuantity(Math.min(5, quantity + 1))} className="rounded-r-lg border border-[#E2ECF6] px-3 py-2">＋</button></div></div>
    <section><p className="mb-2 text-[10px] font-bold uppercase text-[#8C909B]">Delivery method</p><div className="grid grid-cols-2 gap-2">{["Agent Visit", "Pick Up"].map((item) => <button key={item} onClick={() => setDelivery(item)} className={`rounded-xl border p-3 text-left text-sm font-semibold ${delivery === item ? "border-[#2563EB] bg-blue-50" : "border-[#E2ECF6]"}`}>{item}<small className="mt-1 block text-xs font-normal text-[#8C909B]">{item === "Agent Visit" ? "Recommended · Agent visits your location" : "Collect from a nearby hub"}</small></button>)}</div></section>
    <section className="space-y-2"><p className="text-[10px] font-bold uppercase text-[#8C909B]">Delivery address</p><div className="grid grid-cols-2 gap-2"><input value={state} onChange={(e) => setState(e.target.value)} placeholder="State" className="rounded-lg border border-[#E2ECF6] p-2.5 text-sm"/><input value={area} onChange={(e) => setArea(e.target.value)} placeholder="LGA / Area" className="rounded-lg border border-[#E2ECF6] p-2.5 text-sm"/></div><textarea value={street} onChange={(e) => setStreet(e.target.value)} placeholder="Street address" className="min-h-16 w-full rounded-lg border border-[#E2ECF6] p-2.5 text-sm"/><input value={landmark} onChange={(e) => setLandmark(e.target.value)} placeholder="Landmark (optional)" className="w-full rounded-lg border border-[#E2ECF6] p-2.5 text-sm"/><textarea value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Additional notes (optional)" className="min-h-16 w-full rounded-lg border border-[#E2ECF6] p-2.5 text-sm"/></section>
    <div className="flex justify-end gap-2 border-t border-[#E2ECF6] pt-3"><button onClick={close} className="rounded-lg border border-[#E2ECF6] px-4 py-2 text-xs">Cancel</button><button onClick={submit} disabled={!state || !area || !street} className="rounded-lg bg-[#2563EB] px-4 py-2 text-xs font-semibold text-white disabled:opacity-50">Submit Request</button></div>
  </div></AppModal>;
}
