import { useState } from "react";
import { AppModal } from "@/components/common/AppModal";
import { InputOTP, InputOTPGroup, InputOTPSlot } from "@/components/ui/input-otp";
import { openNotification } from "@/utils/notifications";
import type { DeviceSimItem } from "../types/api";

export function SimSwapModal({ open, sim, onClose }: { open: boolean; sim: DeviceSimItem | null; onClose: () => void }) {
  const [step, setStep] = useState(1); const [reason, setReason] = useState(""); const [network, setNetwork] = useState("MTN"); const [keepNumber, setKeepNumber] = useState(true); const [context, setContext] = useState(""); const [pin, setPin] = useState("");
  const close = () => { setStep(1); setReason(""); setNetwork("MTN"); setKeepNumber(true); setContext(""); setPin(""); onClose(); };
  const next = () => { if (step < 3) setStep(step + 1); else { openNotification({ state: "info", title: "Swap request ready", description: "The SIM swap UI is complete, but no swap endpoint is configured yet." }); close(); } };
  const headings = ["SIM Swap", reason === "lost" ? "SIM Swap — Lost SIM" : "SIM Swap — Network Issue", "SIM Swap — Confirm"];
  return <AppModal open={open} onOpenChange={(v) => !v && close()} title={headings[step - 1]} description={step === 1 ? "Select the reason for your swap request" : undefined} size="md"><div className="space-y-4">
    <div className="flex items-center gap-2 text-xs">{[1, 2, 3].map((s) => <span key={s} className={`flex size-6 items-center justify-center rounded-full ${step >= s ? "bg-[#2563EB] text-white" : "bg-slate-100 text-[#8C909B]"}`}>{s}</span>)}</div>
    <div className="rounded-xl bg-slate-50 p-3"><p className="font-bold">{sim?.sim_number || "SIM number unavailable"}</p><p className="mt-1 text-xs text-[#8C909B]">{sim?.network} · {sim?.typeLabel || sim?.sim_type} · Active</p></div>
    {step === 1 && <div className="space-y-2"><p className="text-[10px] font-bold uppercase text-[#8C909B]">Why do you need a swap?</p>{[{ id: "network", title: "Network Issue", sub: "Poor signal, registration or coverage problems" }, { id: "lost", title: "Lost / Stolen SIM", sub: "Your SIM has been lost or is in someone else’s hands" }].map((item) => <button key={item.id} onClick={() => setReason(item.id)} className={`w-full rounded-xl border p-3 text-left ${reason === item.id ? "border-[#2563EB] bg-blue-50" : "border-[#E2ECF6]"}`}><b className="text-sm">{item.title}</b><small className="mt-1 block text-xs text-[#8C909B]">{item.sub}</small></button>)}</div>}
    {step === 2 && (reason === "lost" ? <div className="space-y-3"><p className="rounded-lg bg-amber-50 p-3 text-xs text-amber-800">Your current SIM will be deactivated immediately. The old SIM cannot be reactivated.</p>{[true, false].map((keep) => <button key={String(keep)} onClick={() => setKeepNumber(keep)} className={`w-full rounded-xl border p-3 text-left ${keepNumber === keep ? "border-[#2563EB] bg-blue-50" : "border-[#E2ECF6]"}`}>{keep ? "Keep My Number" : "Get a New Number"}</button>)}<textarea value={context} onChange={(e) => setContext(e.target.value)} placeholder="Describe circumstances (required)" className="min-h-20 w-full rounded-xl border border-[#E2ECF6] p-3 text-sm" /></div> : <div className="space-y-3"><p className="text-[10px] font-bold uppercase text-[#8C909B]">New SIM network preference</p><div className="grid grid-cols-2 gap-2">{["MTN", "Airtel", "Glo", "T2"].map((n) => <button key={n} onClick={() => setNetwork(n)} className={`rounded-xl border p-3 text-sm font-bold ${network === n ? "border-[#2563EB] bg-blue-50" : "border-[#E2ECF6]"}`}>{n}</button>)}</div><textarea value={context} onChange={(e) => setContext(e.target.value)} placeholder="Describe the issue (optional)" className="min-h-20 w-full rounded-xl border border-[#E2ECF6] p-3 text-sm" /><p className="rounded-lg bg-emerald-50 p-3 text-xs text-[#10B981]">Swap fee · Free · Eligible</p></div>)}
    {step === 3 && <><dl className="divide-y divide-[#E2ECF6] rounded-xl border border-[#E2ECF6] px-3 text-xs">{[["Current SIM", `${sim?.sim_number ?? "—"} · ${sim?.network ?? "—"}`], ["Swap reason", reason === "lost" ? "Lost / Stolen SIM" : "Network Issue"], ["New network", reason === "lost" ? network : network], ["Number", keepNumber ? `${sim?.sim_number ?? "—"} (retained)` : "New number"], ["Processing time", "24–48 hours"]].map(([k, v]) => <div key={k} className="flex justify-between py-2"><dt className="text-[#8C909B]">{k}</dt><dd className="font-semibold">{v}</dd></div>)}</dl><p className="rounded-lg bg-blue-50 p-3 text-xs text-blue-800">Your current SIM will continue working until the swap is complete.</p><div className="flex justify-center"><InputOTP maxLength={4} value={pin} onChange={setPin} inputMode="numeric"><InputOTPGroup className="gap-2">{[0, 1, 2, 3].map((i) => <InputOTPSlot key={i} index={i} />)}</InputOTPGroup></InputOTP></div></>}
    <div className="flex justify-between border-t border-[#E2ECF6] pt-3"><button onClick={close} className="rounded-lg border border-[#E2ECF6] px-4 py-2 text-xs">Cancel</button><div className="flex gap-2">{step > 1 && <button onClick={() => setStep(step - 1)} className="rounded-lg border border-[#E2ECF6] px-4 py-2 text-xs">Back</button>}<button disabled={step === 1 && !reason || step === 2 && reason === "lost" && !context.trim() || step === 3 && pin.length !== 4} onClick={next} className="rounded-lg bg-[#2563EB] px-4 py-2 text-xs font-semibold text-white disabled:opacity-50">{step === 3 ? "Confirm Swap" : "Next →"}</button></div></div>
  </div></AppModal>;
}
